# Slicing arrays


Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: `[start:end]`.

We can also define the step, like this: `[start:end:step]`.

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Prints from index 1 to 5 excluding the 5th index
print(arr[1:5])

[2 3 4 5]


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Prints from index 4 to the end of the array
print(arr[4:])

[5 6 7]


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Prints from the beginning to the 4th index not included
print(arr[:4])

[1 2 3 4]


In [15]:
# We can use negative slicing as well to give the index of numbers
# from the back or in reverse order

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Prints from the negative third index to the last ot included
print(arr[-3:-1])

[5 6]


# STEP Slicing
Use the `step` value to determine the step of the slicing:

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Prints every other element in the range
print(arr[1:5:2])

[2 4]


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Prints every other element from the entire array
print(arr[::2])

[1 3 5 7]


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Short cut to reverse arrays using slicing
print(arr[::-1])

[7 6 5 4 3 2 1]


# Slicing 2-D Arrays

In [19]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [20]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [21]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
